### ISSUE TITLE
Deliverable 1 Requirements

### ISSUE THREAD

**Issue by jeremythiboutot** [devinchristianson/daj#18]
Sprint 1 review – Software and Documents
Daily Scrum – The progress should be reported on GitHub and ZenHub. Check the requirements
for this on “Detail of Project Document”.
Update Project Description and User Story documents.
Create Product Backlog and Sprint Backlog documents.
Create the Team Member Report document.
Set up Kanban board on ZenHub and invite Dr. Ghanavati and Ms. Sanonda Gupta as a contributor
to it.
Create the Software Requirements Specification (SRS) document.
Create the Use Case Models and Descriptions document.
Create Sprint Review document.
Create Peer-Review Report document.
Start the software development and push to GitHub as you progress.

**Comment by Dawsinb** [comment]
No longer needed as we are tracking all these issues separately now
