### ISSUE TITLE
Create the Team Member Report document

### ISSUE THREAD

**Issue by Dawsinb** [devinchristianson/daj#22]

**Comment by devinchristianson** [comment]
### Team Member Report
With 1 –2 pages per team member for every sprint – must be created during sprint 1 and updated for every sprint. It includes:
- Team member name.
- Roles played this week.oRole duties and work performed this week, artifacts created/updated/reviewed.
- Role duties and work to be performed next week.
- Issues encountered.
- Issued resolved.
- Percentage of contributions of each team member in the deliverable. Note that the percentage should add up to 100%. The percentage will be checked against GitHub as well.
- Up to one page: Weaknesses and Strengths of the student from peers’ point of view. Reports on  the  improvements  in  compare  to  the  previous  sprint  and  the  plan  for  the  next  sprint’s improvement.
- The file name should be as follows: GroupName_Deliverable_i_TeamMemberReport_j (i = 1..4 and j = 1..6).

**Comment by arevello** [comment]
template and sprint 1 document are uploaded

**Comment by jeremythiboutot** [comment]
Role: Product Owner
Work Done: Product Backlog and Sprint Backlog
Work to be done: Scrum Master next Sprint
Issues Encountered: What the Sprint Backlog should contain
Issues Resolved: Fixed Sprint Backlog
Deliverable Percentage: 10%

**Comment by devinchristianson** [comment]
## Devin Christianson

#### Current Role: Development team

#### Work Done:
- SRS: Sections 1/2
- UseCase doc
- markdown to PDF/UML to PNG to generation pipeline
#### Work to be Done
Development for next sprint
#### Issues Encountered
- Pipeline automation is hard
- Had to learn plantUML
#### Issues Resolved
- Completed working pipeline
- Successfully used plantUML
#### Deliverable Percentage

**Comment by Dawsinb** [comment]
**Team member name:**
Dawsin Blanchard

**Roles played this week. Role duties and work performed this week, artifacts created/updated/reviewed:**
Development team. Created initial application and implemented the core required functionalities (working keyboard, chord recognition set up). Created sprint review document, and helped with the sprint backlog.

**Role duties and work to be performed next week:**
Product owner, focus on guiding the people going on the development team next week as to what needs to be done from the baseline I set up.

**Issues encountered:**
There are many different kinds of chords that we will need to recognize. Slash chords as well have proved to be very difficult to implement. Right now we just have recognition for basic chords in root position.

**Issues resolved:**
Knowledge acquisition regarding chords. We have found a massive database of chords that will help us in implementing non-slash chords. We have some ideas on how we may implement slash chords but are still brain storming.

**Comment by arevello** [comment]
#### Current Role
Developer
#### Work Done
SRS Document sections 4/5, created team member report and peer review template, wrote user stories
#### Work to be Done
User stories TBD
#### Issues Encountered
Lack of time
#### Issues Resolved
N/A
#### Deliverable Percentage
