### ISSUE TITLE
Set up Kanban board on ZenHub and invite Dr. Ghanavati and Ms. Sanonda Gupta as a contributor to it

### ISSUE THREAD

**Issue by Dawsinb** [devinchristianson/daj#23]
Kanban board set up just need to invite Dr. Ghanavati and Ms. Sanonda Gupta

**Comment by devinchristianson** [comment]
Issue Descriptions have been added to each issue for the deliverable 1 milestone.

**Comment by devinchristianson** [comment]
Now that Feren recieved a response to his email, I believe this has been completed.
