### ISSUE TITLE
Create the Software Requirements Specification (SRS) document

### ISSUE THREAD

**Issue by Dawsinb** [devinchristianson/daj#24]

**Comment by devinchristianson** [comment]
### Software Requirements Specification:
Must be created during sprint 1(deliverable 1)and updated as needed. It should follow IEEE SRS guidelineand it includes:
- Functional and Non-functional requirements.
- System and user requirements. 
- Expanded user stories as use cases.
- User interface mockup.
- The file name should be as follows: GroupName_Deliverable_i_SRS (i = 1..4).

**Comment by devinchristianson** [comment]
- [ ] Purpose
- [ ] Product Perspective
- [ ] User Interfaces
- [ ] System Features

**Comment by devinchristianson** [comment]
Going to be working on the Purpose section this morning.

**Comment by devinchristianson** [comment]
First pass on section 1 (Intro) is done. 2 sections were left for once we have done more of the SRS so we know the answers. Going to work on section 2 now
