### ISSUE TITLE
Create the Use Case Models and Use Case Descriptions document

### ISSUE THREAD

**Issue by Dawsinb** [devinchristianson/daj#25]

**Comment by devinchristianson** [comment]
### Use Case Models:
Must be created during sprint 1(deliverable 1)and updated as needed.It includes:
- Use case models.oFor each use case model, use case descriptions include: 
    - usecase descriptions with a unique numbered id
    - the use case name
    - relevant user story ids that pertain to the use case 
    - actors 
    - preconditions 
    - user/system steps 
    - post-conditions 
    - exceptions handled
- The file name should be as follows:GroupName_Deliverable_i_UseCaseModel  (i = 1..4).

**Comment by devinchristianson** [comment]
Skeleton file created. Working on how to convert UML to an image (and what UML format to use)

**Comment by devinchristianson** [comment]
UML generation is working. on the master branch, <filename>.pu (PlantUML) files get converted to PNGs and placed in docs/assets/uml/<filename>.png

Working on Usecase model doc now

**Comment by devinchristianson** [comment]
The first UML diagram, which covers a large number of the use cases, is in. we probably need one or two more to cover some of the farther down the line features
