### ISSUE TITLE
Create Sprint Review document

### ISSUE THREAD

**Issue by Dawsinb** [devinchristianson/daj#26]

**Comment by devinchristianson** [comment]
### Sprint Review Document:
One document with each sprint given its own heading with the following information –Must be created after sprint 1 and updated after each sprint. It includes:
- Sprint Number.
- Features implemented.
- Issues fixed.
- What went well in the implementation, what problems occurred, how problems were solved.
- Changes made.
- What will be done for the next sprint.
- What went well in Scrum, what could be improved, and what changes will be made.oThe file name should be as follows: GroupName_Deliverable_i_SprintReview_j (i = 1..4 and j = 1..6).

**Comment by CastorCannadensis** [comment]
created a markdown file for it

**Comment by Dawsinb** [comment]
Began work on the sprint review document. Everything is done apart from the scrum review section.
