### ISSUE TITLE
Daily Scrum

### ISSUE THREAD

**Issue by Dawsinb** [devinchristianson/daj#29]
The progress should be reported on GitHub and ZenHub. Check the requirements for this on “Detail of Project Document”

**Comment by CastorCannadensis** [comment]
Scrum for 2/25: Coordinated with the group to write the team member report document; talked with the group about roles for the next sprint, organization, etc.
Will work on development during the next sprint.

**Comment by AlexandreFeren** [comment]
Met for the daily scrum (2/25), worked on SRS and Contributions documents. Coordinated to get the next Product Owner and Scrum Master. I will be on the development team in the next sprint.

**Comment by Dawsinb** [comment]
Met for daily Scrum (2/25): worked on SRS a little bit, updated sprint backlog, discussed slightly how the structure of the app is set up and the priorities for next sprint to the dev team.
Going to be the product owner for the next sprint.
--
Did not write down what happened for the previous two scrums, but to retroactively discuss them. I worked on getting a baseline for our application set up and doing the sprint review after the last scrum, and setting up all the documentation for deliverable 1 the scrum before that.

**Comment by devinchristianson** [comment]
Scrum for 2/25 - Worked on SRS, finished UseCase model doc, tidied up all the docs etc. turned everything in. Our meeting focused on what was left to do, and filling out the team member report. Will work on docs and development next sprint.
biggest challenge: markdown embedded images don't scale well

**Comment by jeremythiboutot** [comment]
Scrum 2/25 - Worked on completing team member report. Worked on finishing up and correcting product backlog and sprint backlog. Coordinated roles for next sprint, I will be scrum master next.

**Comment by arevello** [comment]
Scrum 2/25 - Worked on team member report and talked about roles and goals for next sprint. I will be working on product development for the next sprint. Challenges as always are time issues.
