### ISSUE TITLE
Proposal Presentation Guidelines

### ISSUE THREAD

**Issue by jeremythiboutot** [devinchristianson/daj#31]
• The presentation time is about 5 – 6 with 3 – 4 minutes of Q&A from the students.
• The students are expected to provide an overview of their application, what makes their application
stand out in compare to similar applications, their user stories and potentially show a mock-up of
their app or give a demo of what they want to achieve.
• The students are expected to act as entrepreneurs who want to attract venture capital firms for their
app.
• Other students in class are expected to give feedback on the app.
• Other students in class act as clients who are expected to give their high-level requirements to the
presenter team.
• The students must submit their presentation before 11:30AM of the day they present.

**Comment by devinchristianson** [comment]
https://docs.google.com/presentation/d/1TZjnwH0C0FadcBoz3OBlOJFIe1LAd7FticoZUnv9FzQ/edit?usp=sharing

**Comment by devinchristianson** [comment]
Looks like we abandoned the existing google slides doc. heres the new one
https://docs.google.com/presentation/d/1dmo6s95Lwy9aCdcSpXJ_t8VV22gqHy_Un0IfhfcoQi4/edit#slide=id.g6f35caa54f_0_225
