### ISSUE TITLE
Update Documents

### ISSUE THREAD

**Issue by devinchristianson** [devinchristianson/daj#39]
- [x] Project Description and User Story (if required)
- [x] Product Backlog and Sprint Backlog
- [ ] Team Member report
    - needs cleanup
- [x] SRS
- [x] Use Case and Descriptions
    - need user stories on new use cases

**Comment by CastorCannadensis** [comment]
Filling out sprint backlog for deliverable 2, for sprints 2 and 3

**Comment by devinchristianson** [comment]
Accidentally closed -_-

**Comment by devinchristianson** [comment]
Use case model updates still need user stories for both my own and Alex Revello's additions

**Comment by arevello** [comment]
## Alexander Revello
#### Sprint #:  2
#### Current Role
 -Coder
#### Work Done
 -Add MIDI support
 -Create Use Cases
#### Work to be Done
 -Sequence Diagrams
 -Update MIDI support
#### Issues Encountered
 -None
#### Issues Resolved
 -None
#### Deliverable Percentage
 -TBD

**Comment by arevello** [comment]
## Alexander Revello
#### Sprint #:  3
#### Current Role
 -Coder
#### Work Done
 -Created Sequence Diagrams
 -Created data structures for playback
 -Began work on playback
#### Work to be Done
 -Finish playback implementation
 -Begin progression saving and uploading
#### Issues Encountered
 -None
#### Issues Resolved
 -Midi support with octave switching
#### Deliverable Percentage
 -TBD

**Comment by devinchristianson** [comment]
## Devin
#### Sprint #: 2
#### Current Role
 - Developer
#### Work Done
 - Mouse support
 - Sequence Documentation
#### Work to be Done
 - Flask Integration
 - Production Docker container
#### Issues Encountered
 - Difficult translate an existing system to sequence diagrams
#### Issues Resolved
 - Fixed existing issues with the user interface
#### Deliverable Percentage
 - TBD
## Devin
#### Sprint #: 3
#### Current Role
 - Scrumlord
#### Work Done
 - Basic Flask integration
 - Production Docker container
 - Production version deployment workflow created
#### Work to be Done
 - Better Flask integration
#### Issues Encountered
 - Docker auto-build was difficult to work with at first
#### Issues Resolved
 - 
#### Deliverable Percentage
 -

**Comment by AlexandreFeren** [comment]
Sprint 2: 
Role: Product Owner
Work done: Sprint 2 Backlog, Sprint Review 2 doc, Update Product Backlog doc.
Work to be done: Octave switching, document updates.
Issues encountered: None
Deliverable %: TBD

Sprint 3: 
Role: Development team
Work Done: worked on updating SRS, finished implementing octave switching, conducted Focus Group.
Work to be done: find a way to remember users whether through accounts or cookies.
Issues encountered: Firefox has different keycodes than most other browsers for at least ";", "-", and "=".
Deliverable %: TBD

**Comment by jeremythiboutot** [comment]
## Jeremy Thiboutot
#### Sprint 2:  
#### Current Role
 - Scrum Master
#### Work Done
 - Facilitated Scrums
 - Documentation
#### Work to be Done
 - Implementing User Stories
#### Issues Encountered
 - None
#### Issues Resolved
 - None
#### Deliverable Percentage
 - TBD

## Jeremy Thiboutot
#### Sprint 3:  
#### Current Role
 - Development Team
#### Work Done
 - 
#### Work to be Done
 - Implementing new User Stories
#### Issues Encountered
 - None
#### Issues Resolved
 - None
#### Deliverable Percentage
 - TBD

**Comment by AlexandreFeren** [comment]
Deliverable 2 Done
