### ISSUE TITLE
Focus Group

### ISSUE THREAD

**Issue by devinchristianson** [devinchristianson/daj#40]
- [x] Write Script for Focus group
- [x] Perform focus group 
    - [x] must be 4-6 people
    - [x] participants must sign consent form
    - [x] should be one "leader" and one "note-taker" for the focus group
- [x] Create focus group document, which should include:
    - Artifacts
    - Permission Forms
    - Scripts
    - Results
    - Video, if one was taken ( I think we decided not to do this)

**Comment by CastorCannadensis** [comment]
Created the empty focus group document

**Comment by AlexandreFeren** [comment]
Deliverable 2 done
