### ISSUE TITLE
Create Sequence Document

### ISSUE THREAD

**Issue by devinchristianson** [devinchristianson/daj#41]
Should contain:
- [x] Analysis Sequence Diagrams
- [x] Design Sequence Diagrams
- [ ] Correct variables, methods, and parameters
- [ ] Description of steps for each diagram

**Comment by devinchristianson** [comment]
Working on
- [ ] outline document
- [ ] start sequence diagrams/descriptions

**Comment by devinchristianson** [comment]
Working on this again today. 
- [X] design sequence diagram for chord recognition
- [ ] sequence description for chord progression recognition
- [ ] analysis sequence diagram for chord progression
- [ ] use case diagram for login, save

**Comment by devinchristianson** [comment]
accidentally closed -_-

**Comment by devinchristianson** [comment]
Analysis and Design sequence diagrams done for Google Sign-on. Still probably need at least another sequence or two

**Comment by AlexandreFeren** [comment]
Deliverable 2 done
