### ISSUE TITLE
Deliverable 3 Update Documents

### ISSUE THREAD

**Issue by AlexandreFeren** [devinchristianson/daj#65]
- [ ] SRS
  - [x] Write Interface requirements in sections 3.1-3.4
    - [x] 3.1
    - [x] 3.2
    - [x] 3.3
    - [x] 3.4
  - [ ] fix placement of Functional/Non Functional requirements
    - [ ] 4.5.3 - SITE-1 and SITE-2 are NFR
    - [ ] 5.4 - make NFR regarding this section
  - [ ] Updates for Deliverable 3

- [ ] Product Backlog
- [ ] Sprint Backlog
- [ ] Use Case Models/Descriptions
  - [ ] Invoke User stories wherever there is a relevant story
  - [ ] Make Change Synth Sound and Change Octave more detailed
  - [ ] Updates for Deliverable 3

- [ ] Sequence Diagram
- [ ] Domain Model
- [ ] Team Member Report (optional for extra credit)

Where we lost points last Deliverable, details noted above:
Sprint Backlog 2 and 3 - user story IDs do not match with product backlog file
SRS - did not address any of the comments mentioned in Deliverable 1.
Use Case Model and Descriptions - the use cases need an update. 

To try and avoid any miscommunication in this deliverable, if you modify a document, say how you modified it and what needs to be done still to the extent of your ability. Additionally, I am adding notes on where we lost points in the last deliverable to try to facilitate this.

**Comment by AlexandreFeren** [comment]
this deliverable also said to update the Architecture Design document, but I don't see that listed as a requirement for any other deliverable so it will be a "create document" issue.

**Comment by AlexandreFeren** [comment]
My apologies for the lengthy comment, this contains every small update needed for documents as far as I can tell. For the ones without subsections, just update them as you usually would.

**Comment by devinchristianson** [comment]
This is an awesome list!
Also worth noting the team member rep[ort is no longer required

**Comment by arevello** [comment]
I had previously updated the SRS document based on the the deliverable 1 feedback and am now able to notify you all of the changes here

**Comment by devinchristianson** [comment]
Product backlog UserID mismatch was fixed by Jeremy.
